mesosphere/kubeaddons-kommander

addons/kommander/1.x/kommander-9.yaml
- 0.4.8 it is, to include latest KCL release
=> bump version of kommander chart

addons/kommander/1.x/kommander-10.yaml
This was tested on a konvoy cluster and upgrading from version 1.3.0 to the latest version of kommander using the following cluster.yaml entries:
```
- configRepository: https://github.com/mesosphere/kubeaddons-kommander
configVersion: ae/reloader
addonsList:
- name: kommander
enabled: true
- configRepository: https://github.com/mesosphere/kubernetes-base-addons
configVersion: master
addonsList:
...
```
The reloader annotation allows for new cert to be consumed properly and allows clusters to continue to join without a problem. Note that this only happens with this upgrade case. The upgrade from latest to latest case works as expected as no new certificates are created.
=> [D2IQ-61246] using reloader to upgrade properly

addons/kommander/1.x/kommander.yaml
As per [D2IQ-64567](https://jira.d2iq.com/browse/D2IQ-64567) this image override needs to be updated to the latest release provided by the chart.
=> [bug] patch api image overrides

addons/kommander/1.x/kommander.yaml
Bumps Kommander to pull in the latest changes to the chart (fixes a graph on the clusters summary grafana dashboard) https://github.com/mesosphere/charts/pull/460
=> Bump Kommander to 0.4.16

addons/kommander/1.x/kommander.yaml
This should only stay here as an overwrite until we bump the chart version
=> Remove kubernetes 1.15 from UI selection

addons/kommander/1.x/kommander.yaml
https://jira.d2iq.com/browse/D2IQ-64819
This causes Reloader to restart Karma and Thanos deployments when their TLS secrets are modified. Without this PR, Karma and Thanos may use stale certificates, and fail to connect to managed clusters.
I tested this PR by deploying a cluster with the kommander configversion set to this branch:
```
- configRepository: https://github.com/branden/kubeaddons-kommander
configVersion: central-monitoring-reload
addonsList:
- name: kommander
enabled: true
```
I then edited the secrets `kommander-karma-client-tls` and `kommander-thanos-client-tls` in the `kommander` namespace, and observed that the deployments `kommander-kubeaddons-thanos-query` and `kommander-kubeaddons-karma` were restarted with new pods.
=> Reload Karma and Thanos Query on changes to TLS secrets

addons/kommander/1.x/kommander.yaml
⚠️ depends on https://github.com/mesosphere/charts/pull/471 being merged
this bumps latest chart changes on stable-1.16-1.0.0 release branch.
it also includes https://github.com/mesosphere/kubeaddons-kommander/pull/18 and https://github.com/mesosphere/kubeaddons-kommander/pull/23 which originally targeted `master` branch (cc @gracedo & @DanielMSchmidt)
=> [Release branch] 🚄 Kommander GA RC1 Bump

addons/kommander/1.x/kommander.yaml
https://jira.d2iq.com/browse/D2IQ-64819
This is a backport of #22 to stable-1.16-1.0.0.
=> (stable-1.16-1.0.0) Reload Karma and Thanos Query on changes to TLS secrets

addons/kommander/1.x/kommander.yaml
`v0.8.3` includes changes which identify our enterprise repository as a "core" type repository.
=> [chore] update the kommander catalog api server

addons/kommander/1.x/kommander.yaml
This PR is related to the release of kcl; released and bumped to v0.4.10. This includes:
- enable self-attaching Kommander
- chore: bump konvoy to v1.4.0 
- Add cluster count tracking to licenses (#352)
- chore: Use mesosphere build of kubefed
- fix: Check namespace is found before unjoining (#448) 
- chore: bump kubeaddons fed version
- chore: add opsportal roles
- chore: add default dashboard roles to default workspace
- kommander: bump kommander-ui ingress priority (https://github.com/mesosphere/charts/pull/474)
=> update chart version of kommander to 0.4.22

addons/kommander/1.0.x/kommander.yaml
This includes KCL v0.4.11
```
$ git log --pretty=oneline v0.4.10...v0.4.11
0f6948512fe8ea32ab7f84598c6caa08fc823880 feat: use different weight for federated /ops/portal ingress (#451)
e9544300716d33bb3525a153b2ff2e6b0dd759f2 test: add arn roles in a separate test
e3260b21e4fe5cc3f6899f75a8336d8ded8e045d test: fix wrong error message
b093a606729e27a028e466f55e4e7b8be5f68a25 test: configure arn role when the env var is true
369e20af4a3f4755a59975041af2fbef3fe257e0 chore: add new env var to use arn roles
```
=> fix: bump kommander to 0.4.26

test/addons_test.go
The purpose of this PR is to switch off of the old kubeaddons hack for deploying the controller now that we can easily retrieve the `bundle.yaml` to install it.
[D2IQ-64894](https://jira.d2iq.com/browse/D2IQ-64894)
=> [chore] remove old controller deployment hack

addons/kommander/1.0.x/kommander.yaml
This includes KCL v0.5.0:
```
$ git log --pretty=oneline v0.4.11...v0.5.0
D2IQ-65193: Create separate clientapis module (#460)
fix: don't use a finalizer from LicenseClusterCount (#458)
fix: Fix up kommander kubefed requeue intervals
test: deployment ready gomega matcher
chore: move test around
test(e2e): add non-konvoy federated addon assertion
feat: Configurable Konvoy (de)provisioning retries
refactor: Add scheme to controllers helper
fix: fixed instructions in README
chore: bump kubefed version to v0.2.0-alpha.1
chore: Upgrade to kubeaddons 0.9.7
chore: Upgrade golangci-lint to 1.23.7
chore: Fix up broken test flags on darwin
chore: Upgrade to golang 1.14.0
```
=> fix: bump kommander to 0.5.1 (#35)

addons/kommander/1.1.x/kommander.yaml
https://github.com/mesosphere/charts/commits/master/stable/kommander
```
History for charts/stable/kommander
Commits on Mar 25, 2020
[kommander] Revert "chore: move values from addon to chart" (#515) …
@juliangieseke
@alejandroEsc
juliangieseke and alejandroEsc committed 3 minutes ago
[kommander] bump UI & KCL (#519) …
@juliangieseke
juliangieseke committed 31 minutes ago
Commits on Mar 24, 2020
fix: federate karma-proxy only to Konvoy clusters (#516)
@timaa2k
timaa2k committed 16 hours ago
Commits on Mar 23, 2020
chore: move values from addon to chart
@juliangieseke
juliangieseke committed 2 days ago
Commits on Mar 19, 2020
refactor(kommander): Use thanos & karma source code as subcharts (#453)
@samvantran
samvantran committed 6 days ago
Commits on Mar 18, 2020
chore: bump kommander ui …
```
=> chore: bump kommander chart reference 0.5.2 -> 0.5.7

addons/kommander/1.1.x/kommander.yaml
Per [D2IQ-64149,](urhttps://jira.d2iq.com/browse/D2IQ-64149l) we are experiencing the following error when requesting cert from Lets Encrypt: 
`{"level":"info","msg":"legolog: [INFO] [catalog.kubeaddons.localhost] acme: Obtaining bundled SAN certificate","time":"2020-02-11T20:42:58Z"}
{"level":"error","msg":"Unable to obtain ACME certificate for domains \"catalog.kubeaddons.localhost\" detected thanks to rule \"Host:catalog.kubeaddons.localhost\" : unable to generate a certificate for the domains [catalog.kubeaddons.localhost]: acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"catalog.kubeaddons.localhost\": Domain name does not end with a valid public …
=> ingress values for kubeaddons-catalog

addons/kommander/1.1.x/kommander.yaml
adding the ability to pass podAnnotations to the kommander-ui deployment so that we can take advantage of being able to utilize the use of kiam or kube2iam to read from AWS IAM roles from the pod. Per Jira D2IQ-64907
=> podAnnotations to the kommander-ui 

addons/kommander/1.1.x/kommander.yaml
- new version 0.6.16
[D2IQ-67881] #comment kubeaddons-kommander updated
[D2IQ-67881]: https://jira.d2iq.com/browse/D2IQ-67881
=> chore: bump kommander chart version

addons/kommander/1.1.x/kommander.yaml
Depends on https://github.com/mesosphere/charts/pull/587/files
=> chore: bump KCL to v0.6.20

addons/kommander/1.1.x/kommander.yaml
Bumping the Kommander chart to inherit changes introduced by https://github.com/mesosphere/charts/pull/588
=> chore: bump kommander chart to from 0.6.20 to 0.7.1

addons/kommander/1.1.x/kommander.yaml
Bumps kommander chart to 0.8.2 which allows us to add kubecost deployment label
=> chore: Bump kommmander chart to 0.8.2, add kubecost label

addons/kommander/1.1.x/kommander.yaml
We need to release a version to deploy it with Konvoy 1.5.0-rc.1 where yakcl-provisioning is deployed by Konvoy oftb. Therefore we cannot deployed via kommander.
=> chore: bump yakcl chart and disable provisioning module

addons/kommander/1.1.x/kommander.yaml
https://jira.d2iq.com/browse/D2IQ-68100
This bumps the Kommander chart version to pull in https://github.com/mesosphere/charts/pull/626.
I tested this PR  by deploying a Konvoy 1.15 cluster with the Kommander addon's configversion set to this branch. Kommander deploys successfully, `/ops/portal/kommander/kubecost` redirects to `/ops/portal/kommander/kubecost/`, and the Kubecost UI shows the cluster and its projected cost.
=> chore: bump kommander chart

addons/kommander/1.1.x/kommander.yaml
https://jira.d2iq.com/browse/D2IQ-69520
Add reloader annotation to thanos query deployment so it redeploys every time the secret its watching is updated.
=> fix: Add reloader annotation to thanos query deployment

addons/kommander/1.1.0/kommander-41.yaml
Chore
Update kommander chart to include kubecost fixes
- https://github.com/mesosphere/charts/pull/652
- https://github.com/mesosphere/charts/pull/646
no issue
```release-note
NONE
```
**Checklist**
=> chore: bump kommander chart to 0.8.24

addons/kommander/1.1.0/kommander-55.yaml
Chore
Bump kommander to latest chart version 0.8.41 which bumps yakcl deps to 0.1.6
no issue
```release-note
NONE
```
**Checklist**
=> chore: Bump kommander chart to 0.8.41

addons/kommander/1.1.1/kommander-1.yaml
Feature
Bump kommander to 0.8.43 patch version (https://github.com/mesosphere/charts/pull/734) to pull in kubecost upgrades. Once this is merged, I will cut 1.1.1 tags.
D2IQ-70685
I tested this on a cluster and verified that the thanos query offset was set to 5m and costs came up shortly after the cluster was attached.
Depends on https://github.com/mesosphere/charts/pull/736
```release-note
kommander: Aggregated cost monitoring data is now available 5 minutes after clusters are attached
```
**Checklist**
=> [stable-1.1.x] Bump chart to 0.8.43

addons/kommander/1.2.0/kommander-5.yaml
Supercedes #130 
1. If this is your first time, please read our contributor guidelines: https://github.com/mesosphere/kubernetes-base-addons/blob/master/CONTRIBUTING.md
2. When you're changing an existing addon, please do so with at least 2 commits:
1. create a copy of the addon spec file without doing any changes
2. change the copy
That way it’s much easier to review what actually has been changed.
-->
Chore
```release-note
fixes: cannot log out of UI from certain pages
feat: addons can now be upgraded from the catalog UI
feat: view infrastructure providers from the global context
feat: UI enhancements …
```
=> bump kommander ui 1.2 beta

test/go.mod, test/go.sum, test/kommander_test.go
Feature,Chore
New updates to the Kommander addon will trigger an upgrade test from the previous `master` version in CI.
D2IQ-71747
Blocked on https://github.com/mesosphere/kubeaddons/pull/979
NONE
**Checklist**
=> [D2IQ-71747] Add default upgrade testing to CI

addons/kommander/1.2/kommander.yaml, test/artifacts/kubecost-checker.yaml
Removed the aggregatedCostModel endpoint check since in the latest kubecost bump, that endpoint now returns 500s when no data is coming in (expected until clusters are attached).
=> Automated chart bump kommander-0.11.6

addons/kommander/1.2/kommander.yaml
Bug
- bug: fix broken annotation for Kommander addon
- bug: fix storage race condition for Kommander addon
https://jira.d2iq.com/browse/D2IQ-72015
```release-note
- the kommander addon will now wait for a default storage class before deploying in order to support the storage needed for kubecost components
```
**Checklist**
=> [D2IQ-72015] Fix storage race condition for Kommander addon

addons/kommander/1.2/kommander.yaml
bug: remove the delete strategy from Kommander addon
The delete strategy was only triggered on very old versions of Kubeaddons,
however at this point we fully expect that Kommander should NEVER be
delete upgraded as to protect against deletion of federated resources.
This change should generally not really have any effect, but if nothing else should reduce confusion related to the annotation.
This is one of the situations where it is safe (in fact preferable) to remove this annotation without needing to bump the revision for the Addon.
=> Use the default upgrade strategy for Kommander

addons/kommander/1.2/kommander.yaml
Chore
This bumps the Addon to the latest chart version, pulling in the latest catalog API server version.
several
```release-note
```
**Checklist**
=> chore: use latest chart version

addons/kommander/1.2/kommander.yaml, test/vars_test.go
Bug
https://jira.d2iq.com/browse/D2IQ-72328
```release-note
Prevent a race condition where kube-cost PVCs were being created before the default StoragaClass preventing PVs from being created.
```
**Checklist**
=> fix: requires-storageclass is a label not an annotation

README.md, addons/kommander/1.3/kommander.yaml, mergebot-config.json
1.2 now lives on https://github.com/mesosphere/kubeaddons-kommander/tree/stable-1.2.x branch.
=> Initial 1.3 Master Setup

addons/kommander/1.2/kommander.yaml, test/vars_test.go
Chore/feature
Bump to 0.12.1 which updates cert-manager resources to v1 (in yakcl)
https://jira.d2iq.com/browse/D2IQ-72175
This is going into `stable-1.2.x` branch.
```release-note
feat: Update cert-manager resources to v1
```
**Checklist**
=> [stable-1.2.x] Bump chart to 0.12.1 to support cert-manager v1 upgrade

addons/kommander/1.1/kommander.yaml
Chore.
Bump kommander to 0.8.45 in stable-1.1.x branch.
`values.chart.helm.kubeaddons.mesosphere.io/kommander` has beenset to the latest SHA in the `release/kommander-0.8.x` of mesosphere/charts.
```release-note
Set kommander chart version to 0.8.45.
```
**Checklist**
=> [stable-1.1.x] Bump chart version to 0.8.45

addons/kommander/1.2/kommander.yaml
Chore/bug
Bump to latest chart version which includes yakcl bump (https://github.com/mesosphere/yakcl/pull/243)
https://jira.d2iq.com/browse/D2IQ-70795
When this is merged (to stable-1.2.x) I will cut rc.3
```release-note
Adds automatic creation of KommanderProjectRole and VirtualGroupKommanderProjectRoleBinding objects based on Workspace objects.
```
**Checklist**
=> chore: Bump chart to 0.12.3

addons/kommander/1.2/kommander.yaml
Chore/bug
Bump kommander/yakcl to pull in bug fix in mesosphere/yakcl#249
```release-note
Fixes a bug that prevents the prometheus-operator chart from being uninstalled
Fixes a bug in kubeaddons that causes an endless reconcile when a helm chart is partially installed, but not in a deployed state _and_ there are resources in the manifest that are not ready.
Fixes a bug when `KommanderWorkspaceRole` controller fails to create `ClusterRole` when its spec is missing `WorkspaceObjectVerbs` definition.
Adds `WorkspaceObjectVerbs` definition to default `KommanderWorkspaceRole`s.
```
**Checklist**
=> [1.2.x] chore: Bump chart to 0.12.6

addons/kommander/1.2/kommander.yaml
not 100% sure what 0.12.7 bumped and why its not yet in the addon.
```release-note
feat: remove conductor addon
feat: link to infra providers if that is why cluster can't delete
fix: remove finalizers from kommander clusters when force deleted (COPS-6626)
fix: reverted limiting service account to fix upgrade issue
```
**Checklist**
=> [1.2] bump chart 0.12.6 -> 0.12.8

addons/kommander/1.2/kommander.yaml
Bug
Wait for the cert-manager addon to be upgraded to v1 before starting the upgrade of Kommander.
```release-note
Wait for cert-manager to be upgraded and use v1 API before upgrading Kommander.
```
**Checklist**
=> [1.2] Add a new requires cert-manager: v1

addons/kommander/1.0/kommander.yaml
The 1.0.x release of this addon was using the 0.4 version of the chart.
Konvoy shipped with 1.0.2 which used chart 0.4.31. Since upstream helm
charts are removing their stable repository from google, we need to
point the subcharts of that chart to our own fork of the upstream repo.
This requires using the 0.4.31 chart and only changing the repo url in
requirements.yaml.
```release-note
```
**Checklist**
=> [1.0] chore: bump kommander chart to 0.4.32 

addons/kommander/1.2/kommander.yaml
I _think_ this was replaced by the utility server anyway, but lets keep it for release - not sure if something is still depending on it 🙈 
```release-note
```
**Checklist**
=> [1.2] chore: update k8s minSupportedVersion

addons/kommander/1.2/kommander.yaml
Chore
Bump kommander to latest version to pull in latest changes in https://github.com/mesosphere/charts/pull/892
https://jira.d2iq.com/browse/D2IQ-71985
```release-note
Fix access to kubecost UI for some cluster roles
```
**Checklist**
=> [1.2] chore: Bump chart to 0.12.14

test/kommander_test.go
Signed-off-by: Dimitri Koshkin <dimitri.koshkin@gmail.com>
Chore
After [recent kubeaddons changes](https://github.com/mesosphere/kubeaddons/pull/1062), the kubeaddons-controller will now fail on a delete error.
Currently, Kommander cannot be deleted, so removing it from the list of addons to cleanup.
```release-note
```
**Checklist**
=> [1.2] e2e: Skip Kommander cleanup at the end

test/kommander_test.go
Signed-off-by: Dimitri Koshkin <dimitri.koshkin@gmail.com>
Chore
After [recent kubeaddons changes](https://github.com/mesosphere/kubeaddons/pull/1062), the kubeaddons-controller will now fail on a delete error.
Currently, Kommander cannot be deleted, so removing it from the list of addons to cleanup.
```release-note
```
**Checklist**
=> e2e: Skip Kommander cleanup at the end

addons/kommander/1.3/kommander.yaml
chore
master is outdated pointing to 0.12.10. The latest release went out on 0.12.16, we should at least update master to point to that same version (which is vetted as it has been released). CI will fail on upgrade test since it deletes the addon and kommander fails to uninstall (https://jira.d2iq.com/browse/D2IQ-73310) but it should be fine to merge this in while we look into fixing kommander uninstall
```release-note
```
**Checklist**
=> chore: Bump to 0.12.16

Dispatchfile
We were tracking tags while release triggers were being developed on Dispatch. Now release triggers work.
No
```release-note
NONE
```
**Checklist**
=> Dispatchfile: track releases instead of tags

addons/kommander/1.3/kommander.yaml
Chore
Bump yakcl and kommander/opsportal UIs to latest
```release-note
chore: Bump kubecost to 0.5.1
chore: Use calico 3.16.4 w/1.6
chore: Use konvoy1.5 on prem
chore: Add workspace default cluster labels validation
feat: create default network policy for projects
feat: add project labels to project namespace and federatednamespace
feat: create project network policies through the UI
feat: manage workspace addons
feat: integrate dispatch CD into projects
```
**Checklist**
=> Automated chart bump kommander-0.13.14

addons/kommander/1.3/kommander.yaml
chore
bump yakcl to v0.7.2
```release-note
feat: Add Kubernetes v1.16-v1.19 support for all federated addons/clusteraddons
chore: Bump prometheus federated addon to 9.3.5
chore: Bump go.mod for Konvoy with k8s 1.19
```
**Checklist**
=> Automated chart bump kommander-0.13.15

addons/kommander/1.3/kommander.yaml
Fix
In related to CVE-2017-14062, used in bitnami/kubectl@1.16 is normally used in one-liners to talk to the API. I am not sure how critical is the usage of libidn2 for those one-run calls. 
```
Integer overflow in the decode_digit function in puny_decode.c in Libidn2 before 2.0.4 allows remote attackers to cause a denial of service or possibly have unspecified other impact.
```
```release-note
```
**Checklist**
=> Automated chart bump kommander-0.13.21

addons/kommander/1.3/kommander.yaml
Signed-off-by: Dimitri Koshkin <dimitri.koshkin@gmail.com>
Bug
Similar change as https://github.com/mesosphere/charts/pull/964/files
```
k logs -n kommander      kommander-kubeaddons-set-grafana-home-dashboard-trigger-7gs2h
sh: /bin/bash: not found
```
```release-note
Kommander: fix set-grafana-home-dashboard after it was updated to a new jq image.
```
**Checklist**
=> Automated chart bump kommander-0.13.28

addons/kommander/1.2/kommander.yaml, test/kommander_test.go
bug
Bump chart for kubecost version bump to fix bug https://github.com/mesosphere/charts/pull/986. This will go into `1.2.x` stable branch to be released in kommander 1.2.1 patch (w/ konvoy 1.6.x patch don't actually know which is the next patch version 😬 )
```release-note
fix: Bump kubecost to fix an issue that occasionally caused pods to fail to deploy
fix: Ensure pre-delete hook jobs are cleaned up
fix: Ensure kubectl deletes do not fail if resource already deleted
```
**Checklist**
=> [1.2.x] Bump kommander kubecost

addons/kommander/1.3/kommander.yaml, mergebot-config.json
bug
Chart uninstall may get stuck at 
```
Warning  DriverDeployFailure  46m (x5 over 70m)    kubeaddons-controller  could not delete release: warning: Hook pre-delete kommander/templates/grafana/opsportal-username-secret.yaml failed: jobs.batch "cleanup-kommander-kubeaddons-ops-portal-username" already exists
```
The hook was missing a `before-hook-creation` delete annotation to ensure we don't run into the above error.
This needs to go into kommander 1.1/1.2/1.3 / konvoy 1.5/1.6/1.7 patches. Will backport this to the relevant chart versions. This kommander bump will go into komm1.3/konv1.7 patch
https://jira.d2iq.com/browse/D2IQ-74255
https://jira.d2iq.com/browse/COPS-6821
**Special …
=> [1.3.x] Automated chart bump kommander-0.13.36

addons/kommander/1.3/kommander.yaml
bug
Bump kommander-ui to fix non-konvoy cluster platform services page https://github.com/mesosphere/kommander-ui/pull/3292. Would be great to include this in the next kommander 1.3.1 patch release.
https://jira.d2iq.com/browse/D2IQ-74138
```release-note
fix): Fix empty non-Konvoy cluster Platform Services tab 
```
**Checklist**
=> [1.3.x] bump kommander-0.14.0

README.md, addons/kommander/1.4/kommander.yaml
chore
Bumps all the versions post 1.3 GA to prep for 1.4. 
```release-note
chore: Bump federated fluentbit to 0.7.1
fix: Bump kubecost to 0.5.4 to ensure kubectl deletes do not fail if resource already deleted
chore: Bump federated reloader to v0.0.80
feat: Bump go deps dependencies to konvoy
```
**Checklist**
=> Bump chart to 0.16.1

addons/kommander/1.4/kommander.yaml
Chore
This creates a label that allows gatekeeper to mutate pods and inject correct proxy settings. 
https://jira.d2iq.com/browse/D2IQ-70021
```release-note
None
```
**Checklist**
=> chore: adding namespace label for gatekeeper proxy mutations

addons/kommander/1.3/kommander.yaml
bug
Bumps kommander to latest patch version for 1.3.x. Includes yakcl and kommander-ui bumps
https://jira.d2iq.com/browse/D2IQ-74140
https://jira.d2iq.com/browse/COPS-6821
https://jira.d2iq.com/browse/D2IQ-74255
https://jira.d2iq.com/browse/D2IQ-74458
https://jira.d2iq.com/browse/D2IQ-73852
https://jira.d2iq.com/browse/COPS-6844
```release-note
fix: All federated addons/clusteraddons will now be successfully removed when Kubeaddons is disabled
fix(kubecost): Ensure kubectl deletes do not fail if resource already deleted 
fix: Reverts previous change to projects. Before, it created a default …
```
=> [1.3.x] Bump kommander to 0.15.2

addons/kommander/1.4/kommander.yaml
Feature
Adds support for tunneled clusters to karma. The karma must be deployed with a custom version from https://github.com/mesosphere/karma/tree/v0.55-d2iq-proxy
https://jira.d2iq.com/browse/D2IQ-74658
```release-note
Support tunneled clusters in karma configuration
```
**Checklist**
=> [auto-bump][chart] kommander-0.19.1

addons/kommander/1.4/kommander.yaml
Bumps yakcl to v0.11.0 and kommander-ui to 6.92.0 which turns on the helm releases feature (backend released in yakcl v0.11.0)
```
feat: Add kubetunnel integration
fix: Default labels are now getting passed into federation controller manager deployment
feat: Adds controller that deploys cluster-observer addon per kommandercluster
feat: Show status of Helm Releases in Kommander UI
```
=> [auto-bump][chart] kommander-0.21.0

addons/kommander/1.4/kommander.yaml
chore
bump yakcl to latest v0.13.0
```release-note
* feat: Bump federated Kubeaddons to v0.26.0
* fix: Fix proxy service naming bug
* feat: Bump kubetunnel version to v0.0.5
* fix: Duplicate namespaces no longer created per workspace
* fix: FederatedKubeaddons controller no longer errors if there are no managed resources that need finalizers applied
* feat: Add mtls-proxy secrets sync controller
```
**Checklist**
=> [auto-bump][chart] kommander-0.23.0

addons/kommander/1.4/kommander.yaml
* bump kommander-ui to v6.93.0 - D2IQ-73887
Feature
UI update to add support for catalog addon (platform service) badges, certified, air-gapped, supported.
[D2IQ-73887](https://jira.d2iq.com/browse/D2IQ-73887)
```release-note
- UI: adds support for Catalog platform service badges to identify certified, air-gapped and d2iq supported platform services.
```
**Checklist**
=> [auto-bump][chart] kommander-0.24.0

addons/kommander/1.3/kommander.yaml, test/kommander_test.go
bug
Bumps kommander-ui in kommander (https://github.com/mesosphere/charts/pull/1083)
Bumps kubecost, bumps yakcl
https://jira.d2iq.com/browse/D2IQ-74749
```release-note
- fix: UI update to handle new KUDO param types
- feat: Enables PodSecurityPolicy in Kubecost
- fix: No duplication of namespaces for a single workspace, anymore
- fix: FederatedKubeaddons controller no longer errors if there are no managed resources that need finalizers applied
```
**Checklist**
=> [1.3.x] Bump kommander-ui, kubecost, yakcl

addons/kommander/1.4/kommander.yaml
chore
bump yakcl to latest
```release-note
- UI: adds ability to attach clusters with network restrictions
- chore: Bump federated kubecost to v0.9.0
- chore: Bump kubetunnel version to v0.0.6
- chore: Bump cluster-observer to v0.1.1
```
**Checklist**
=> [auto-bump][chart] kommander-0.28.0

addons/kommander/1.4/kommander.yaml
Bug
This bumps the karma subchart to pull in #1107. This removes the liveness probe, which could cause the karma container to be unnecessarily restarted if any of its backing alertmanagers are slow to respond, potentially preventing its API from becoming available.
This replaces the `livenessProbe` values with `readinessProbe` values. Previous versions of the karma chart used the `livenessProbe` values for the container's `readinessProbe`, so there is effectively no change to readiness checks.
no issue
```release-note
[kommander] Updates the karma subchart to remove a liveness probe that could cause the …
```
=> [auto-bump][chart] kommander-0.29.1

addons/kommander/1.4/kommander.yaml
chore
Now, we run the publish job automatically on pushes to `release/*` branches so that we no longer need to manually run `make publish` on those branches on updates. This has been tested on this PR https://github.com/mesosphere/charts/pull/1104 going into `release/kommander-0.15.x` which ran the Dispatch publish job, resulting in the chart publish to `gh-pages` 🥳 https://github.com/mesosphere/charts/commit/f199f12d4b6c8bf1d34758c70828028c1ef902cc. FYI, for any other existing release branches, we still need to cherry-pick this Dispatchfile change to get this triggered on that branch. So far, this has been added to `release/kommander-0.15.x` and `release/prometheus-operator-9.3.x`
h/t @faiq for the help :D 
**Which …
=> [auto-bump][chart] kommander-0.29.4

addons/kommander/1.4/kommander.yaml
chore
bump yakcl to latest
```release-note
- fix: Update UI dependencies to mitigate CVE-2021-23337
- fix: Federated addon info is now displayed properly in UI cards
- fix: Bumps federated Kubeaddons to v0.26.1 to fix a bug causing unnecessary addon deployment delays
- feat: Upgrades federated Prometheus to 12.11.10, which includes a change to use the kube-prometheus-stack upstream chart following the deprecation of helm/charts.
```
**Checklist**
=> [auto-bump][chart] kommander-0.30.0

addons/kommander/1.4/kommander.yaml
bug
bumps kubecost to latest to fix pvc sizing issue. this is a backport to 1.4.x
Will open backport for komm1.3. we can use this for 1.4 since no non-1.4 changes have gone into the chart since last release
```release-note
fix(kubecost): Increase default cost-analyzer persistent volume size to 32Gi. Upgrades may require manual intervention if your provisioner does not support volume expansion. (COPS-6937)
feat(kubecost): Migrate to new Allocation view. Legacy view to remain available at /detail.html
```
**Checklist**
=> [1.4.x] Bump kommander to 0.32.0

addons/kommander/1.3/kommander.yaml
bug
bumps kubecost to latest to fix pvc sizing issue. this is a backport to 1.3.x
Will open backport for komm1.3. we can use this for 1.4 since no non-1.4 changes have gone into the chart since last release
```release-note
fix(kubecost): Increase default cost-analyzer persistent volume size to 32Gi. Upgrades may require manual intervention if your provisioner does not support volume expansion. (COPS-6937)
feat(kubecost): Migrate to new Allocation view. Legacy view to remain available at /detail.html
```
**Checklist**
=> [1.3.x] Bump chart to 0.15.11

addons/kommander/1.5/kommander.yaml
bug
bumps kubecost to latest to fix pvc sizing issue. will backport to 1.4.x
Will open backport for komm1.3. we can use this for 1.4 since no non-1.4 changes have gone into the chart since last release
```release-note
fix(kubecost): Increase default cost-analyzer persistent volume size to 32Gi. Upgrades may require manual intervention if your provisioner does not support volume expansion. (COPS-6937)
feat(kubecost): Migrate to new Allocation view. Legacy view to remain available at /detail.html
```
**Checklist**
=> fix: Bump kommander to 0.32.0

README.md, addons/kommander/1.4/kommander.yaml, mergebot-config.json
chore
Since we may not ever be releasing kommander 1.5, let's revert the addon revision in `master` back to 1.4 so that we can continue to work off `master` instead of backporting every change to `1.4.x`. We should try to remember to merge `master` back into `1.4.x` so it does not get too far behind in case we ever do release a 1.5 qnd need to start using the 1.4.x release branch.
```release-note
NONE
```
**Checklist**
=> chore: Revert addon revisions back to 1.4

addons/kommander/1.3/kommander.yaml
bug
Bump kubecost for pvc bug fix, this is for federated kubecost (vs kommander centralized kubecost which has been bumped).
This backports to 1.3.x
https://jira.d2iq.com/browse/COPS-6937
```release-note
NONE (already mentioned)
```
**Checklist**
=> [1.3.x] Bump kommander to 0.15.12

addons/kommander/1.4/kommander.yaml
This bump includes handling of KUDO params in kommander
bug fix for documentation links
bug fix to only show the catalog addon stage badge a single time
Bug(s)
```release-note
- UI: support KUDO number, integer & boolean parameter types
- fix UI: updated documentation links
- fix UI: only show catalog service stage badge a single time
```
**Checklist**
=> [auto-bump][chart] kommander-0.35.1

addons/kommander/1.3/kommander.yaml
```release-note
fix: Bumps federated traefik-forward-auth to version 3.0.1 which addresses some security issues
fix: Remove federated grafana dashboard cm (COPS-6999) (#437)
```
**Checklist**
=> [1.3.x] chore: Bump kommander to 0.15.14

mergebot-config.json
Chore
Technically, we don't have any plans to release Kommander 1.5.0 but any merges to master branch should reflect the next minor version. 
Right now merging to master means JIRA tickets get tagged with Kommander 1.4.1 and backporting commits to `1.4.x` branch means the same tickets get updated with `1.4.3` which is confusing.
Note: when we release Kommander 1.4.3 we'll need to update this file again.
=> chore: update mergebot-config release version

addons/kommander/1.4/kommander.yaml
Closes D2IQ-81807
Feature: [Adds socket monitoring](https://github.com/mesosphere/kommander-ui/commit/37f63d5e851943b6994894602ce782be591bbab7)
Fix: [Pins docker version](https://github.com/mesosphere/kommander-ui/commit/fd51337c218ea9c3b7296ed442cd54459bc473f0)
There is an issue where Kommander UI runs out of ports. This monitors ports and forces a restart if it runs out.
**Checklist**
=> [auto-bump][chart] kommander-0.38.4

addons/kommander/1.4/kommander.yaml
chore
in prep for 1.4.4 release we need to bump the appversion annotations (we should have bumped this after 1.4.3 was released 😬 )
```release-note
```
**Checklist**
=> chore: Bump appversion to 1.4.4
