README.md

does that sound right for now? needs improvement, for sure. but as a first guideance for people working with this repo?

docs: add short term guideance to readme

---

addons/kommander/1.0.x/kommander.yaml

this bumps the last versions of thanos, karma and the ui

bump karma, thanos, ui

---

addons/kommander/1.1.x/kommander.yaml

blocked by https://github.com/mesosphere/charts/pull/565/files

chore: bump kcl

---

addons/kommander/1.0.x/kommander.yaml

[1.0.x] Kommander 1.0.1 bits n pieces 

---

addons/kommander/1.1.x/kommander.yaml

https://jira.d2iq.com/browse/D2IQ-65414
https://jira.d2iq.com/browse/D2IQ-67855
Bump kommander chart to 0.6.18

chore: Bump kommander chart version

---

README.md

this should add some information on how we deal with kommander when it comes to releases. please read and let me know if something isnt crystal clear 🙇 
note: this PR documents the existing process, nothing new is introduced

document current release steps and add step by step guides

---

test/artifacts/kubecost-checker.yaml
test/kommander_test.go
test/kubecost_test.go

https://jira.d2iq.com/browse/D2IQ-67940

test: Add kubecost e2e tests

---

addons/kommander/1.1.x/kommander.yaml

Depends on mesosphere/charts#604

chore: bump chart reference

---

addons/kommander/1.1.x/kommander.yaml

RC 1 got tagged today, going forward everything thats merged to master will be RC 2.

Update Kommander AppVersion to RC 2

---

addons/kommander/1.1.x/kommander.yaml

https://jira.d2iq.com/browse/D2IQ-68979

feat: only expose K8s version >=1.16.0 from utility API server

---

addons/kommander/1.1.x/kommander.yaml

This enables impersonation and kubecost in the UI

Bump chart 0.8.10

---

addons/kommander/1.1.x/kommander.yaml

Update Karma/Thanos versions in Metadata

---

addons/kommander/1.1.x/kommander.yaml

Bump chart to latest version to pull in https://github.com/mesosphere/charts/pull/632

chore: Bump chart

---

addons/kommander/1.1.0/kommander-40.yaml

Chore
Brings us all the beauty of YAKCL v0.1.2.
```release-note
```
**Checklist**

chore: bumps kommander chart

---

addons/kommander/1.1.0/kommander-42.yaml

Chore
Bump Chart
Multiple
```release-note
[UI] update to 3.110.0
```
**Checklist**

Bump Chart 0.8.25

---

addons/kommander/1.1.0/kommander-43.yaml

Chore
Bump the chart
```release-note
Bump the chart version of the addon
```
**Checklist**

chore: bump kommander chart

---

addons/kommander/1.1.0/komander-44.yaml

Chore
We need this for the releases according to the directive given in https://jira.d2iq.com/browse/D2IQ-69478?focusedCommentId=337639&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-337639
https://jira.d2iq.com/browse/D2IQ-69478
```release-note
```
**Checklist**

chore: set allowUnofficialReleases to false

---

addons/kommander/1.1.0/kommander-44.yaml

Chore
Bump kommander version to latest version to pull in https://github.com/mesosphere/charts/pull/659
https://jira.d2iq.com/browse/D2IQ-69505
```release-note
NONE
```
**Checklist**

Bump kommander to 0.8.29

---

addons/kommander/1.1.0/kommander-45.yaml

Chore
Bump Kommander to 0.8.31
no issue
```release-note
```
**Checklist**

Bump Kommander to 0.8.31

---

addons/kommander/1.1.0/kommander-46.yaml

Chore
Bump Kommander to 0.8.32
no issue
```release-note
```
**Checklist**

Bump Kommander to 0.8.32

---

addons/kommander/1.1.0/kommander-47.yaml

Chore
Reapply #105 which looks to have been overwritten by #106. Both of these prs probably worked off the same previous revision (43) and bumped to 44, and since #106 was merged after #105, it overwrote the changes introduced in #105. This PR reintroduces that change.
```release-note
```
**Checklist**

chore: Reapply #105 (set allowUnofficialReleases to false)

---

addons/kommander/1.1.0/kommander-48.yaml

Chore
Critical UI bug fix- after merging I will retag master to v1.1.0-rc.5
no issue
```release-note
```
**Checklist**

1.1 kommander chart bump to 0.8.33

---

addons/kommander/1.1.0/kommander-49.yaml

Chore
Bump kommander to latest version
https://jira.d2iq.com/browse/D2IQ-69513
```release-note
NONE
```
**Checklist**

chore: Bump kommander to 0.8.34

---

addons/kommander/1.1.0/kommander-50.yaml

Chore
no issue
Blocked on https://github.com/mesosphere/charts/pull/681
```release-note
NONE
```
**Checklist**

chore: Upgrade kommander to 0.8.35

---

.github/PULL_REQUEST_TEMPLATE.md
mergebot-config.json

CI
adding mergebot automation for fixversions
```
jql=key in (D2IQ-69922)
```
```release-note
```
**Checklist**

Add mergebot-config for automated fixVersion

---

addons/kommander/1.1.0/kommander-51.yaml

Depends on mesosphere/charts#686 
Chore
Bump kommander chart
Remove catalog override: https://jira.d2iq.com/browse/D2IQ-69905
UI bump: 
```
jql=labels in ( ksphere-ui:v3.126.1, ksphere-ui:v3.126.0, ksphere-ui:v3.125.4, ksphere-ui:v3.125.3, ksphere-ui:v3.125.2, ksphere-ui:v3.125.1, ksphere-ui:v3.125.0, ksphere-ui:v3.124.2, ksphere-ui:v3.124.1, ksphere-ui:v3.124.0, ksphere-ui:v3.123.0, ksphere-ui:v3.122.5, ksphere-ui:v3.122.4, ksphere-ui:v3.122.3)
```
**Checklist**

Kommander chart bump

---

README.md

```release-note
```
**Checklist**

Update README.md (add mergebot)

---

addons/kommander/1.1.0/kommander-52.yaml

Chore
Bump Addon
Use Kommander chart version 0.8.38
```
no issue
```
```release-note
```
**Checklist**

Bump Addon

---

addons/kommander/1.1.0/kommander-54.yaml

Chore
Bump kommander chart to latest version to pull in latest kubecost version
no issue
Blocked until https://github.com/mesosphere/charts/pull/692 is merged
```release-note
NONE
```
**Checklist**

chore: Upgrade kommander to 0.8.40

---

addons/kommander/1.1.0/kommander-55.yaml

Chore
Update appversion to rc.7
no issue
```release-note
NONE
```
**Checklist**

chore: Update appversion to rc7

---

README.md
addons/kommander/1.1.0/kommander-56.yaml
mergebot-config.json

Chore
Update mergebot-config.json and kommander appversion to rc8 (if we expect next version to be stable release, I can change these)
no issue
```release-note
NONE
```
**Checklist**

chore: Update mergebot-config and appversion to rc8

---

addons/kommander/1.0.2/kommander-1.yaml

Bug
Bump kommander to 0.4.31 patch version
https://jira.d2iq.com/browse/D2IQ-70046
```release-note
```
**Checklist**

stable-1.0.x: bump kommander chart to 0.4.31

---

addons/kommander/1.1.0/kommander-57.yaml

But
Bump chart to 0.8.42 which includes fix for https://jira.d2iq.com/browse/D2IQ-70196. 
https://jira.d2iq.com/browse/D2IQ-70196
When this is merged (into the stable branch), I will re-tag 1.1.0 and also merge latest stable branch into master
```release-note
NONE
```
**Checklist**

chore: Upgrade chart to 0.8.42

---

addons/kommander/1.1.0/kommander-57.yaml

Chore
Merge `stable-1.1.x` back into master after changes + retagging `v1.1.0`
no issue
```release-note
NONE
```
**Checklist**

Merge stable-1.1.x into master

---

addons/kommander/1.2.0/kommander-4.yaml
test/kommander_test.go
test/vars_test.go

Chore
This PR is to allow helm3 deployment of kommander, 
This PR should not be merged yet, it may change and depends also on having the following PR merge:
https://github.com/mesosphere/charts/pull/756
```release-note
Kommander now deploys with helm3
```
**Checklist**

kommander release via helm3

---

addons/kommander/1.2.0/kommander-5.yaml

Chore
Bump Kommander chart version
```release-note
```
**Checklist**

chore: bump kommander

---

mergebot-config.json

Update merbot-config.json to bump to the next version after releasing 1.1.2

chore: Update mergebot-config

---

addons/kommander/1.2.0/kommander-6.yaml

Chore
Bumping Kommander chart version
```release-note
```
**Checklist**

chore: manual bot bumping kommander

---

addons/kommander/1.2.0/kommander-7.yaml

Chore
Bump kommander to `0.11.1` which brings https://github.com/mesosphere/yakcl/pull/185
* jql=key in (D2IQ-71389)
* https://jira.d2iq.com/browse/D2IQ-71389
```release-note
NONE
```
**Checklist**

chore: bump to kommander 0.11.1

---

addons/kommander/1.2.0/kommander-8.yaml

```release-note
```
**Checklist**

chore: manual bot v2 bumping kommander

---

addons/kommander/1.2.0/kommander-9.yaml
test/bundle.yaml
test/vars_test.go

Chore
Bump of kommander chart
```release-note
```
**Checklist**

chore: manual bump of kommander

---

addons/kommander/1.2.0/kommander-10.yaml

- https://jira.d2iq.com/browse/D2IQ-70983
- https://jira.d2iq.com/browse/D2IQ-66331
- https://jira.d2iq.com/browse/D2IQ-71018
- https://jira.d2iq.com/browse/D2IQ-70543
- https://jira.d2iq.com/browse/D2IQ-65247
- https://jira.d2iq.com/browse/D2IQ-71452
- https://jira.d2iq.com/browse/D2IQ-71280
- https://jira.d2iq.com/browse/D2IQ-70553
- https://jira.d2iq.com/browse/D2IQ-70664
- https://jira.d2iq.com/browse/D2IQ-70561
- https://jira.d2iq.com/browse/D2IQ-71202
- https://jira.d2iq.com/browse/D2IQ-71349
- https://jira.d2iq.com/browse/D2IQ-71350
- https://jira.d2iq.com/browse/D2IQ-71353
```release-note
fix: …
```

bump kommander-ui 1.2 beta to ui image 6.31.6

---

addons/kommander/1.2/kommander.yaml

Chore
- vsphere added as enabled provider
jql=key in (D2IQ-71902)
[D2IQ-71902]
[D2IQ-71902]: https://jira.d2iq.com/browse/D2IQ-71902
```release-note
vSphere enabled
```
**Checklist**

chore: [vsphere] enabled kommander for new provider

---

Dispatchfile

Every time someone makes a new tag that matches the latest few commits on master, create a pull request on mesosphere/konvoy-soak to update the cluster.yaml to this new version of kommander.
https://jira.d2iq.com/browse/D2IQ-71917
**Checklist**

Add Dispatchfile

---

addons/kommander/1.2/kommander.yaml

https://jira.d2iq.com/browse/D2IQ-72080
Add release note or "none":
```release-note
fixed bug with catalog items not showing up
```

Automated chart bump kommander-0.11.16

---

addons/kommander/1.2/kommander.yaml

Add release note or "none":
```release-note
All federated resources are now deleted as soon as Kommander is uninstalled.
```

Automated chart bump kommander-0.11.17

---

addons/kommander/1.2/kommander.yaml

Add release note or "none":
```release-note
```

Automated chart bump kommander-0.11.18

---

addons/kommander/1.2/kommander.yaml

Chore
Update kommander to 0.12.2 (to go into 1.2)
https://jira.d2iq.com/browse/D2IQ-72706
https://jira.d2iq.com/browse/D2IQ-72695
```release-note
NONE
```
**Checklist**

[stable-1.2.x] chore: Update chart to 0.12.2

---

addons/kommander/1.1/kommander.yaml

chore
point to chart that uses our fork for subcharts since the upstream chart repo is going away
I used to think I was indecisive. But now I’m not so sure.
```release-note
none
```
**Checklist**

[stable-1.1.x] Bump chart version to 0.8.46

---

addons/kommander/1.2/kommander.yaml

backport of #206 
https://jira.d2iq.com/browse/D2IQ-72847

[1.2] chore: bump chart to latest version

---

addons/kommander/1.2/kommander.yaml

```release-note
yakcl v0.6.6
```
**Checklist**

[1.2] bump chart 0.12.9 -> 0.12.10

---

addons/kommander/1.2/kommander.yaml

Chore
Bump kommander to 0.12.15
```release-note
```
**Checklist**

chore: bump kommander chart version to 0.12.15

---

addons/kommander/1.2/kommander.yaml

Chore
Bump chart to latest
```release-note
Pulls in kubefed release 0.5.1 which includes:
* chore: make certain cert-manager properties configurable.
* fix: klog verbosity detection.
```
**Checklist**

[1.2.x] Bump kommander to 0.12.16

---

addons/kommander/1.3/kommander.yaml
test/kommander_test.go

Chore
Upgrade kubecost to latest version (https://github.com/mesosphere/charts/pull/914)
no issue
```release-note
NONE
```
**Checklist**

Automated chart bump kommander-0.13.4

---

test/kommander_test.go

bug in test
In the previous test fix, the change was made to deploy kommander in the upgrade test first to avoid needing to uninstall it, then run tests. I didn't cover the case for when upgrade tests are not necessary (in the case when chart is not bumped) then kommander isn't getting installed at all (doh!). Added a fix here to add kommander into the addon deploy list if upgrade tests aren't happening.
```release-note
NONE
```
**Checklist**

test: Fix to deploy kommander if upgrade test not necessary

---

addons/kommander/1.3/kommander.yaml

First bump after renaming the UI repo - some CI changes were necessary - 🤞 that I did it correct.
```release-note
Bump UI to 6.67.0
```
**Checklist**

Automated chart bump kommander-0.13.5

---

addons/kommander/1.3/kommander.yaml

Chore
Update yakcl to latest release v0.7.0
no issue
```release-note
kommander: Update yakcl to v0.7.0
```
**Checklist**

Automated chart bump kommander-0.13.6

---

addons/kommander/1.3/kommander.yaml

- Edit Network Policies: D2IQ-72937
- Fix Limit Range memory: COPS-6728
```release-note
```
**Checklist**

Automated chart bump kommander-0.13.7

---

mergebot-config.json

Chore
Bump mergebot-config now that beta0 is out
```release-note
```
**Checklist**

chore: Bump mergebot-config

---

addons/kommander/1.3/kommander.yaml

Chore
Update kubecost to latest
no issue
```release-note
NONE
```
**Checklist**

Automated chart bump kommander-0.13.8

---

addons/kommander/1.3/kommander.yaml

chore
update kubecost to latest
no issue
```release-note
NONE
```
**Checklist**

Automated chart bump kommander-0.13.9

---

addons/kommander/1.3/kommander.yaml

Chore
Bump opsportal and kommander ui chart
**Checklist**

Automated chart bump kommander-0.13.10

---

addons/kommander/1.3/kommander.yaml

chore
bump yakcl to latest release
no issue
```release-note
feat: Add federated addons data structure configmap
feat: Update kubecost to v0.5.0
feat: Add workspace cluster labels controller
chore: Bump kommander-licensing memory limit to 512Mi
```
**Checklist**

Automated chart bump kommander-0.13.11

---

addons/kommander/1.3/kommander.yaml

Refactoring
Cleans up the duplication of chart values introduced by https://github.com/mesosphere/charts/pull/880
```release-note
```
**Checklist**

Remove default overrides

---

addons/kommander/1.3/kommander.yaml

chore
bump kubecost to latest
no issue
```release-note
NONE
```
**Checklist**

Automated chart bump kommander-0.13.12

---

addons/kommander/1.3/kommander.yaml

chore
Bump kommander-ui to latest in kommander and opsportal charts
```release-note
```
**Checklist**

Automated chart bump kommander-0.13.13

---

addons/kommander/1.3/kommander.yaml

```release-note
```
**Checklist**

chore: Bump annotation to rc.1

---

addons/kommander/1.3/kommander.yaml
mergebot-config.json

now that rc1 is out, bump to rc2 in annotation and mergebot-config
```release-note
```
**Checklist**

chore: Bump rc version

---

addons/kommander/1.3/kommander.yaml

Chore
Update kommander/opsportal UI
```release-note
NONE
```
**Checklist**

Automated chart bump kommander-0.13.16

---

addons/kommander/1.3/kommander.yaml

chore/feat
update yakcl to v0.8.0
```release-note
feat: Kubernetes dependencies updated to 1.19 (#318)
```
**Checklist**

Automated chart bump kommander-0.13.17

---

addons/kommander/1.3/kommander.yaml
mergebot-config.json

```release-note
```
**Checklist**

chore: Updates after 1.3.0 rc2 release

---

addons/kommander/1.3/kommander.yaml

```release-note
```
**Checklist**

Automated chart bump kommander-0.13.19

---

addons/kommander/1.3/kommander.yaml

```release-note
chore: Bump yakcl to v0.8.1
```
**Checklist**

Automated chart bump kommander-0.13.20

---

addons/kommander/1.3/kommander.yaml
mergebot-config.json

```release-note
```
**Checklist**

chore: updates after rc3 release

---

addons/kommander/1.3/kommander.yaml

bug
bump yakcl to latest to fix CVE-2017-14062
```release-note
fix: CVE-2017-14062 (Integer overflow in the decode_digit function in puny_decode.c in Libidn2 before 2.0.4 allows remote attackers to cause a denial of service or possibly have unspecified other impact)
```
**Checklist**

Automated chart bump kommander-0.13.23

---

addons/kommander/1.3/kommander.yaml
mergebot-config.json

```release-note
```
**Checklist**

chore: rc version bumps after release

---

addons/kommander/1.3/kommander.yaml

Chore
Bump UI for kommander/opsportal
```release-note
```
**Checklist**

Automated chart bump kommander-0.13.24

---

addons/kommander/1.3/kommander.yaml

Chore
Bump UI for kommander/opsportal
```release-note
NONE
```
**Checklist**

Automated chart bump kommander-0.13.25

---

addons/kommander/1.3/kommander.yaml

bug / chore
Update yakcl to v0.8.3 and kubecost to 0.5.2 to mitigate CVEs
```release-note
chore: Update yakcl to v0.8.3
fix: Update Prometheus and Kubecost (federated addons) to mitigate CVEs
fix: Mitigate CVEs in Kibana and Fluentbit (federated addons)
chore: Remove Fluentbit's dependency on Elasticsearch (federated addons)
chore: Increase number of Elasticsearch data replicas to 4 (federated addon)
fix: Update Kubecost to mitigate CVEs
```
**Checklist**

Automated chart bump kommander-0.13.26

---

addons/kommander/1.3/kommander.yaml
mergebot-config.json

```release-note
```
**Checklist**

chore: Bump versions after rc5

---

addons/kommander/1.3/kommander.yaml

```release-note
```
**Checklist**

chore: Bump kommander chart version to pull in CVE fixes

---

addons/kommander/1.3/kommander.yaml

chore
bump kubecost to latest which includes massive perf improvements as well as some fixes to regression in prev version
```release-note
significant performance improvements in kubecost
```
**Checklist**

Automated chart bump kommander-0.13.29

---

addons/kommander/1.3/kommander.yaml

Chore
Bump kommander k8s-sidecar to 1.3.0 to align and fix CVEs
```release-note
NONE
```
**Checklist**

Automated chart bump kommander-0.13.30

---

addons/kommander/1.3/kommander.yaml

chore/bug
bump kubecost to pull in cve fix
```release-note
```
**Checklist**

Automated chart bump kommander-0.13.31

---

addons/kommander/1.3/kommander.yaml

Chore
Fix release blocker bug
```release-note
```
**Checklist**

Automated chart bump kommander-0.13.32

---

addons/kommander/1.3/kommander.yaml

chore
bump yakcl to latest
```release-note
chore: Bump yakcl to v0.8.4
```
**Checklist**

Automated chart bump kommander-0.13.33

---

addons/kommander/1.3/kommander.yaml

bug
Pull in downgraded kubecost (https://github.com/mesosphere/charts/pull/988) and (TODO) upgrade yakcl once https://github.com/mesosphere/yakcl/pull/339 is released
https://jira.d2iq.com/browse/D2IQ-74109
```release-note
```
**Checklist**

Automated chart bump kommander-0.13.34

---

addons/kommander/1.3/kommander.yaml

bug
bump yakcl to bring in blocker bug fix
https://jira.d2iq.com/browse/D2IQ-74136
```release-note
```
**Checklist**

Automated chart bump kommander-0.13.35

---

addons/kommander/1.1/kommander.yaml

bug
Bump chart to v0.8.47, includes some fixes we will release in v1.1.4/konv1.5.x
https://github.com/mesosphere/charts/pull/998
https://jira.d2iq.com/browse/D2IQ-74255
https://jira.d2iq.com/browse/COPS-6821
```release-note
fix: Ensure pre-delete hook jobs are cleaned up
fix: Ensure kubectl deletes do not fail if resource already deleted
```
**Checklist**

[1.1.x] Bump chart to v0.8.47

---

addons/kommander/1.4/kommander.yaml
mergebot-config.json

chore
bump kubecost to latest https://github.com/mesosphere/charts/pull/1005
```release-note
chore(kommander): Enable PodSecurityPolicy in federated kubecost
```
**Checklist**

[auto-bump][chart] kommander-0.17.0

---

addons/kommander/1.3/kommander.yaml

chore
Bumps kommander-ui to pull in latest changes/patches (including these inn the next kommander patch release)
I'm trying to start actually following semver for chart version bumps now - so bumping the minor version on both charts since the kommander-ui subchart minor version was bumped
```release-note
fix(kommander-ui): disable addons on foundation disabled
feat(kommander-ui): add license delete mutation
feat(kommander-ui): replace license table with single license detail view
feat(kommander-ui): allow workspace namespace to be configurable
```
**Checklist**

[1.3.x] [auto-bump][chart] kommander-0.15.0

---

addons/kommander/1.3/kommander.yaml

bug
```release-note
fix: Ensure finalizer is set on kubeaddons after re-enabling it
```
**Checklist**

[1.3.x] Bump kommander to 0.15.3

---

addons/kommander/1.4/kommander.yaml

Bug
fixes bug for COPS-6843---before Identity Providers would not show up, now it does.
COPS-6843
```release-note
Fixes bug in OpsPortal where Identity Providers would not show up
```
**Checklist**

[auto-bump][chart] kommander-0.17.3

---

addons/kommander/1.4/kommander.yaml

Bug
Updated to UI v6.91.1 this includes a COPS fix and updates the UI docker image to only install production deps which should cut down the UI having CVEs that are not relevant.
[COPS-6844](https://jira.d2iq.com/browse/COPS-6844)
```release-note
fix: Fixes bug in OpsPortal & Kommander UI where LDAP Root CA is malformed when saved
fix: Update UI to only ship with needed dependencies
```
**Checklist**

[auto-bump][chart] kommander-0.18.0

---

addons/kommander/1.4/kommander.yaml

automated bumps for chore: batch requirements 0.10.0

[auto-bump][chart] kommander-0.19.0

---

addons/kommander/1.2/kommander.yaml
mergebot-config.json

bug
Bump kommander to pull in UI fix https://github.com/mesosphere/charts/pull/1053. This will go into the next 1.2.2 patch release
https://jira.d2iq.com/browse/D2IQ-74644
```release-note
fix: UI allows deleting license & show license details
```
**Checklist**

[1.2.x] Bump kommander to 0.12.20

---

Dispatchfile
test/go.sum

https://jira.d2iq.com/browse/D2IQ-74160

Auto Bump Kubeaddons Kommander

---

addons/kommander/1.4/kommander.yaml

Feature
In addition to existing `FederatedSecrets` with TLS certificate and key for `mtls-proxy` create also a local copy of server certificate data that can be used for local management cluster `mtls-proxy` instances.
https://jira.d2iq.com/browse/D2IQ-74659
```release-note
```
**Checklist**

[auto-bump][chart] kommander-0.19.3

---

addons/kommander/1.3/kommander.yaml

chore
Backport UI improvements https://github.com/mesosphere/charts/pull/1049
https://jira.d2iq.com/browse/D2IQ-74321
```release-note
fix: Update license page copy in kommander-ui
```
**Checklist**

[1.3.x] Bump chart to 0.15.4

---

addons/kommander/1.3/kommander.yaml

bug
bump kommander to latest https://github.com/mesosphere/charts/pull/1070
no issue
```release-note
fix: Default labels are now getting passed into federation controller manager deployment
```
**Checklist**

[1.3.x] Bump kommander to 0.15.5

---

addons/kommander/1.4/kommander.yaml

```release-note
```
**Checklist**

chore: disable service monitor kubetunnel

---

Dispatchfile

* Fix the Dispatch Trigger wherein tag is given in the invocation.
UNKNOWN / TODO - What will be the tag value when given in chatops. I will test it and verify it.
**Checklist**

Specify Tag in the invocation.

---

addons/kommander/1.4/kommander.yaml
mergebot-config.json
test/kommander_test.go

chore
Bumps to rc.1 and also improves test to check against the base branch for upgrade testing (so tests on release branches can run against the correct base instead of against master which is ahead)
```release-note
NONE
```
**Checklist**

Bumps to 1.4.0-rc.1

---

addons/kommander/1.3/kommander.yaml

Bug
Bump UI to fix bug updating GitOps Source objects in Projects.
[D2IQ-74943](https://jira.d2iq.com/browse/D2IQ-74943)
```release-note
- Fix UI to update GitOps Source in a project without failing
```
**Checklist**

[1.3] Bump kommander-ui

---

addons/kommander/1.4/kommander.yaml

Bug
Updated to kommander-ui to 6.98.0 which resolves issues in kommander and omits dev deps
from the docker image.
https://jira.d2iq.com/browse/D2IQ-74745
https://jira.d2iq.com/browse/D2IQ-75347
```release-note
- UI - resolve kubecost performance issue
- UI - handle license loading state, show loading instead of invalid when license is missing a status
```
**Checklist**

[auto-bump][chart] kommander-0.31.0

---

addons/kommander/1.4/kommander.yaml

bug
bump yakcl to latest which includes a bug fix
https://jira.d2iq.com/browse/COPS-6897
https://jira.d2iq.com/browse/D2IQ-75354
```release-note
fix: Workspace admin roles are now automatically propagated to projects within the workspace.
```
**Checklist**

[auto-bump][chart] kommander-0.31.1

---

addons/kommander/1.3/kommander.yaml

bug
bump kommander to latest to pull in UI fixes https://github.com/mesosphere/charts/pull/1120
https://jira.d2iq.com/browse/D2IQ-74745
https://jira.d2iq.com/browse/D2IQ-75347
https://jira.d2iq.com/browse/D2IQ-75054
```release-note
- UI: Resolve kubecost performance issue
- UI: Handle license loading state, show loading instead of invalid when license is missing a status
```
**Checklist**

[1.3.x] bump kommander to 0.15.10

---

addons/kommander/1.4/kommander.yaml
mergebot-config.json

chore (maintenance to merge 1.4.x version bumps for GA back to master from newly created 1.4.x release branch)
```release-note
NONE
```
**Checklist**

chore: Bump versions for GA

---

README.md
addons/kommander/1.5/kommander.yaml
mergebot-config.json

chore
rename dir, version bumps etc after releasing 1.4.0. I guess I'm not sure if we will have a 1.5 but bumping anyways to follow process :)
```release-note
NONE
```
**Checklist**

Updates after 1.4.0 GA

---

addons/kommander/1.4/kommander.yaml

bug
Bump kubecost for pvc bug fix, this is for federated kubecost (vs kommander centralized kubecost which has been bumped)
https://jira.d2iq.com/browse/COPS-6937
```release-note
NONE (already mentioned)
```
**Checklist**

chore: Bump to 0.33.0

---

addons/kommander/1.4/kommander.yaml

automated bumps for chore: batch requirements 0.18.0

[auto-bump][chart] kommander-0.35.0

---

addons/kommander/1.3/kommander.yaml

chore
bump chart to pull in https://github.com/mesosphere/charts/pull/1154
no issue
```release-note
NONE
```
**Checklist**

[1.3.x] bump chart to 0.15.13

---

addons/kommander/1.4/kommander.yaml

automated bumps for chore: batch requirements 0.19.0
Bumps yakcl to latest release
https://github.com/mesosphere/yakcl/releases/tag/v0.19.0

[auto-bump][chart] kommander-0.37.0

---

addons/kommander/1.4/kommander.yaml

chore
want to cut rc.1 for 1.4.2 patch, so need to revise the version here. when this is merged I will cut `v1.4.2-rc.1` tags
```release-note
```
**Checklist**

chore: Use 1.4.2-rc.1

---

addons/kommander/1.4/kommander.yaml

automated bumps for chore: batch requirements 0.20.0

[auto-bump][chart] kommander-0.38.0

---

mergebot-config.json

Chore
Update mergebot config with new fixversions so that JIRA tickets get the right fixV whenever PRs merge

chore: update mergebot config fixversions

---

addons/kommander/1.4/kommander.yaml

automated bumps for chore: batch requirements 0.20.1

[auto-bump][chart] kommander-0.38.1

---

addons/kommander/1.4/kommander.yaml

fix: update socks library & code: https://github.com/mesosphere/kommander-ui/commit/2495fab8938f3e5aa97bbea9386a20f32b761323
This fixes a kubetunnel  issue
```release-note
```
**Checklist**

[auto-bump][chart] kommander-0.38.5

---

addons/kommander/1.4/kommander.yaml

Bug
Adds the concurrency policy `Replace` configuration to the set home dashboards `CronJob` to avoid potentially creating an unbound number of pods if a pod is failing to start.
https://jira.d2iq.com/browse/COPS-7105
```release-note
NONE
```
**Checklist**

[auto-bump][chart] kommander-0.38.6

---

addons/kommander/1.4/kommander.yaml

automated bumps for chore: batch requirements 0.21.0

[auto-bump][chart] kommander-0.39.0

---

addons/kommander/1.4/kommander.yaml

automated bumps for chore: batch requirements 0.21.1

[auto-bump][chart] kommander-0.39.1

---

addons/kommander/1.4/kommander.yaml

automated bumps for chore: batch requirements 0.21.2

[auto-bump][chart] kommander-0.39.2
